"""Data models for document generation, styling, and rendering."""

from typing import Optional, Dict, Any
from pathlib import Path
from pydantic import BaseModel, Field, ConfigDict

from core.constants import DocumentType, ThemeName
from core.models.profile import MasterProfile


class StyleOptions(BaseModel):
    """Visual design tokens passed to the LaTeX template."""
    font_size: str = Field(default="10pt", description="LaTeX font size: '9pt', '10pt', '11pt', '12pt'")
    margin_top: str = Field(default="0.6in", description="Page top margin")
    margin_bottom: str = Field(default="0.6in", description="Page bottom margin")
    margin_left: str = Field(default="0.6in", description="Page left margin")
    margin_right: str = Field(default="0.6in", description="Page right margin")
    primary_color: str = Field(default="#1E293B", description="Hex accent color (titles/rules)")
    line_spacing: float = Field(default=1.1, description="Relative line height multiplier")


class TailoredDocument(BaseModel):
    """A tailored document payload ready for typesetting."""
    document_type: DocumentType = Field(default=DocumentType.RESUME)
    target_job_title: Optional[str] = None
    target_company: Optional[str] = None
    profile: MasterProfile
    cover_letter_content: Optional[str] = None
    bio_content: Optional[str] = None
    gap_summary: Optional[str] = None


class RenderRequest(BaseModel):
    """Parameters passed to the LaTeX rendering engine."""
    document: TailoredDocument
    theme: ThemeName = Field(default=ThemeName.CLASSIC)
    style: StyleOptions = Field(default_factory=StyleOptions)
    output_path: Optional[str] = None


class RenderResult(BaseModel):
    """Output artifact generated by the LaTeX compiler."""
    success: bool
    pdf_bytes: Optional[bytes] = None
    latex_source: str
    output_pdf_path: Optional[str] = None
    compilation_log: str = ""
    compile_time_seconds: float = 0.0

    model_config = ConfigDict(arbitrary_types_allowed=True)
